[general]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[env]
WINIT_X11_SCALE_FACTOR = "1.25"

[window]
padding = {x = 10, y = 10}
dynamic_padding = true
decorations = "Full"
opacity = 0.75
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = true
level = "Normal"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = {family = "FantasqueSansM Nerd Font Mono", style = "Regular"}
bold = {family = "FantasqueSansM Nerd Font Mono", style = "Bold"}
italic = {family = "FantasqueSansM Nerd Font Mono", style = "Italic "}
bold_italic = {family = "FantasqueSansM Nerd Font Mono", style = "Bold Italic"}
size = 13.25
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
primary.background = "#181818"
primary.foreground = "#d8d8d8"
transparent_background_colors = true

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = {program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"]}

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = {shape = "Underline", blinking = "Always"}
vi_mode_style = {shape = "Underline", blinking = "Always"}
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = [
	{mouse = "Middle", mods = "None", action = "Paste"}
]

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
